name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug secrets
        run: |
          echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
          echo "VPS_USER: ${{ secrets.VPS_USER }}"
        shell: bash

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          if [ -z "${{ secrets.VPS_HOST }}" ]; then
            echo "Error: VPS_HOST is not set!"
            exit 1
          fi
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Pull latest changes on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /var/www/html/your-project && git pull origin main && npm install && pm2 restart all"
